builders:
  use_case_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["useCaseBuilder"]
    build_extensions: { ".dart": [".usecase.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":app_builder", ":telemetry"]
    build_to: cache
    defaults:
      options:
        # Possible values: "component" or "use_case"
        # For more info:
        # https://docs.widgetbook.io/guides/customization#using-nav_path_mode-option
        nav_path_mode: component

  app_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["appBuilder"]
    build_extensions: { ".dart": [".directories.g.dart"] }
    auto_apply: dependents
    build_to: source

  addons_configs_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["addonsConfigsBuilder"]
    build_extensions: { ".dart": [".config.widgetbook.json"] }
    auto_apply: dependents
    build_to: cache

  telemetry:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["reportTelemetry"]
    build_extensions: { ".directories.g.dart": [".track"] }
    required_inputs: [".directories.g.dart"]
    auto_apply: root_package
    build_to: cache
    defaults:
      options:
        debug: false

  experimental_story_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["storyBuilder"]
    runs_before: [":experimental_components_builder"]
    build_extensions: { ".stories.dart": [".stories.book.dart"] }
    auto_apply: none # Disabled by default
    build_to: source
    defaults:
      generate_for:
        - lib/**.stories.dart

  experimental_components_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["componentsBuilder"]
    build_extensions: { ".stories.dart": [".dart"] }
    auto_apply: none # Disabled by default
    build_to: source
